name: PipelineAS1

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: 

jobs:
  build-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: instala dependencias Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: instala dependencias
      run: npm install
    - name: realiza criacao da pasta build
      run: npm run build
    - name: Log in to Docker registry
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}  
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:latest .
    - name: Push Docker image to registry
      run: |
        docker push ${{ secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:latest

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npm run lint

      
      

  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{secrets.TAG}}
      - name: Run Docker container 
        run: |
          docker run -d -p 8080:80 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}}:${{secrets.TAG}}
